README.md

[feat]REDMEを編集

---

app/layout.tsx

resolve #11 
layout.tsxを編集して背景画像を挿入
画面の大きさを変えても中央下を中心に正しく画面全体を覆うか確認
追加したコード部分
人が少なくて寂しい感じがしなくもないのでもうちょっとにぎやかにして今後差し替えるのもありかと思いました

[feat]layout.tsxのclassNameを編集してバックグラウンドに画像を表示

---

app/layout.tsx

resolve #15 
app/layout.tsxのclassNameを修正してローカルフォントが適用されない問題に対応しました。

[fix]ローカルフォントが適用されない問題を修正

---

app/components/footer.tsx
app/components/header.tsx

resolve #22 
Link機能を使って実装
Link機能を使って実装

ロゴをクリックでtopページに飛ぶ機能の実装

---

app/components/header.tsx

resolve #26 
ハンバーガーメニューを実装しました
ヘッダー内にハンバーガーメニューの処理を記述した

[#26]ハンバーガーメニューを実装しました

---

app/components/back_frame.tsx
app/pages/top/page.tsx

resolve #37 
上下が少しグラデーションになっている背景を作成しました
back_frame.tsxを作成、編集
PCサイズ(768px以上)で横幅400px固定
</br>
</br>
スマホサイズ(768px未満)で画面全体を覆う
</br>
</br>
スクショ部分のコードは以下の通りです（コンフリクトでないように一回消しておきました）
ページ毎にインポートする必要があります

中央の白い背景のコンポーネントを作成

---

app/components/line.tsx

resolve #36  
<Line>で赤線のコンポーネントを使えます（マージンの設定は無し）

[feat]赤線の装飾コンポーネントを追加

---

app/pages/example/page.tsx
app/pages/top/page.tsx

exampleページを作成、topページの内容を引っ越し

---

app/components/footer.tsx
app/components/header.tsx
tailwind.config.ts

resolve #47 
ヘッダーフッダー専用の色を設定、ヘッダーとフッターに適用

ヘッダーフッダーの色を変更

---

package-lock.json
package.json

react-iconsをインストール

---

app/components/line.tsx

resolve #56 
line.tsxを編集し、classNameを追加で設定できるようにしました
これにより線の色を変えることができます

Lineの色を変更できるようにコンポーネントを修正

---

app/components/link_button.tsx
app/pages/example/page.tsx
tailwind.config.ts

resolve #51 
外部リンク、内部リンクを指定して機能するボタンを追加
・isExternal={true}で外部リンク、{false}で内部リンク（初期値はfalse）
・hrefで飛ぶリンクを指定
・classNameで追加の装飾
メール機能のボタンについてやり方を検討中です

ボタンコンポーネントを実装

---

app/components/frame.tsx
app/globals.css
app/pages/top/components/recruitment_sponsors.tsx
app/pages/top/page.tsx

resolve #59 
協賛募集セクションにスパム対策を施したメールアドレス表示・コピー機能を実装しました。
1. スパム対策の実装
- メールアドレスコピーボタンのテキスト内にダミーテキストを挿入
2. JavaScriptでメールアドレスを動的に構築
- クリップボードAPIを使用してコピー機能を実装
- コピー完了時のフィードバック表示を追加
- JavaScriptコードはボットから直接読み取られにくいため、変数として定義したメールアドレスの一部分がスパム送信先として収集されるリスクが減りますー
Frameコンポーネントの横幅が狭いため、少し調節させていただいてます。
スパム対策として、メールアドレスをそのまま表示せず、ボタンクリック時にのみコピーできる形式を採用しました。

feat:協賛募集セクションの作成

---

app/components/frame.tsx
app/components/text_style.tsx
app/pages/top/components/top_attentions.tsx
app/pages/top/page.tsx

top内のcomponentsにtop_attention.tsxとしてコンポーネントを作成しました
改行位置を多少デザインから変更しています
space-y-6とかがうまく機能しなくてヤンキーみたいなパディングの付け方をしてるのでうまいやり方知ってたら教えてください...

技大祭を楽しむためにセクションの作成

---

.prettierrc.json
.vscode/settings.json

VScodeとprettirの設定を追加

---

app/pages/top/components/Infos.tsx

resolve #75 
エラー時のお知らせFrameの修正
お知らせのエラー文にフレームを追加
修正前
修正後

エラー時のお知らせFrameの修正

---

app/components/carousel.tsx
app/pages/example/page.tsx
app/pages/top/components/top_attentions.tsx

[fix]Eslintを撃破

---

app/pages/top/page.tsx
package-lock.json
package.json

cloudfrarepagesの設定を追加

---

package-lock.json

[feat]npm isntallを実行

---

app/pages/top/page.tsx
next.config.mjs
open-next.config.ts
package-lock.json
package.json

[feat]open何とかを追加

---

src/app/layout.tsx

[fix]消してしまったフォントの設定を追加

---

next.config.mjs
package-lock.json
package.json

[feat]svgrの設定を追加（svgガビガビ対策）

---

src/app/page.tsx
src/components/common/footer.tsx
src/components/common/header.tsx
src/components/common/return_top_button.tsx

svgrをsvg画像に適用

---

src/components/common/back_frame.tsx
src/components/common/frame.tsx
src/components/common/header.tsx

resolve #0
フレームとバックフレームの幅調整
ハンバーガーメニューの閉じるボタンの位置調整
フレームとバックフレームの幅調整
- 画面幅に合わせて幅が変わるようにした。
ハンバーガーメニューの閉じるボタンの位置調整
- ハンバーガーメニューに開くボタンと閉じるボタンの位置を一致させた。

[fix]フレームとハンバーガーメニューのCSS調製

---

package-lock.json
package.json
scripts/download-images.mjs
src/data/exh_exp.json

resolve #0
pacage.jsonにenvのことを書かないようにしてます。

[fix]デプロイ時のエラー修正

---

src/app/access/page.tsx
src/components/access/date_section.tsx

アクセスページのレイアウトを作成

---

src/app/food/[id]/page.tsx
src/app/food/page.tsx
src/components/food/CellContent.tsx

[feat]食品販売一覧デザインの作成

---

src/app/corpolate_booth/[id]/page.tsx
src/app/corpolate_booth/page.tsx
src/components/corpolate_booth/CellContent.tsx

resolve #151 
企業ブースページの詳細ページのデザイン作成
・URL部分と出店番号は今のところ不要のためコメントアウトしました

【企業ブース】idページデザイン作成

---

src/app/food/page.tsx
src/app/sale/[id]/page.tsx
src/app/sale/page.tsx
src/components/sale/CellContent.tsx

resolve #132 
物販一覧ページのデザインを作成した
加えて食販ページの不要なイベントページへボタンを削除した

物販ページ一覧デザイン作成

---

src/components/common/tag_modal.tsx

[fix]タグモーダルを２列に

---

src/components/common/footer.tsx

resolve #180 
footerにコラボリンクを追加した。

【TOPページ】footerにコラボリンク追加

---

src/components/common/detail_map.tsx

[fix]ESLintのエラー回避、不要なインポートの削除

---

src/app/access/page.tsx
src/app/corpolate_booth/page.tsx
src/app/event/exh_exp/page.tsx
src/app/event/guest/page.tsx
src/app/event/page.tsx
src/app/event/plan/page.tsx
src/app/food/page.tsx
src/app/globals.css
src/app/page.tsx
src/app/sale/page.tsx
src/components/event/random_banner.tsx

resolve #184 
・各ページに広告配置
・TOPに幼稚園宣伝セクション配置
・イベントページに枠デザイン追加
・企画、展示体験を「詳しく見る」から「もっと見る」に

広告配置＋細かい修正

---

src/app/greeting/page.tsx

resolve #0
・挨拶ページの「先」を「千」に修正
・不要なコードの削除

挨拶ページの修正＋不要なコードの削除
